version: "3.7"
services:
    app:
        build:
            args:
                user: tutorha
                uid: 1000
            context: ./
            dockerfile: ./docker/Dockerfile
        image: tutorha
        container_name: tutorha-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - tutorha
    nginx:
        image: nginx:alpine
        container_name: tutorha-nginx
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx_dir/nginx_conf:/etc/nginx/conf.d/
            - ./docker/nginx_dir/certs:/etc/nginx/certs
        networks:
            - tutorha
    mysql:
        image: mariadb
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        volumes:
            - ./docker/volumes/mariadb:/var/lib/mysql
        networks:
            - tutorha
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" , "-h", "localhost" ]
            retries: 3
            timeout: 5s
    mysql2:
        image: mariadb
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        volumes:
            - ./docker/volumes/mariadb2:/var/lib/mysql
        networks:
            - tutorha
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" , "-h", "localhost" ]
            retries: 3
            timeout: 5s
    redis:
        image: 'bitnami/redis:latest'
        ports:
            - '6379:6379'
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - ALLOW_EMPTY_PASSWORD=no
        networks:
            - tutorha
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 9000:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql
        networks:
            - tutorha
        depends_on:
            - mysql
networks:
    tutorha:
        driver: bridge
